### ISSUE TITLE
stock ammo cant be changed by server

### ISSUE THREAD

**Issue by VierEck** [siecvi/zerospades#1]
aloha.pk babel is the only server that changes the maximum stock ammo. 

rifle players for instance have 75 ammo in stock instead of just the default 50. 
(smg and shotgun are also affected)

However on ZeroSpades you only end up with 50 maximum stock ammo on that server. 

what the server says goes, clients have to oblige to that. Its also just unfair when u end up with just 50 ammo while everyone else can enjoy to have 75. 

![image](https://user-images.githubusercontent.com/85409780/168138309-2e104cc7-eadb-46b5-bbe1-6fea58c207d8.png)
the bug is from Client/NetClient.cpp line 1352. top line is the original line from zerospades version as of now which is responsible for the bug. 
the beneath line is from yvt's original openspades source code which fixes the bug.

**Comment by siecvi** [comment]
Fixed by https://github.com/siecvi/zerospades/pull/1
