### ISSUE TITLE
Failed to compile in Kubuntu 22.04

### ISSUE THREAD

**Issue by adam-adrian** [siecvi/zerospades#5]
[terminal-log.txt](https://github.com/siecvi/zerospades/files/9024405/terminal--log.txt)

Looks like because permission denied.

**Comment by adam-adrian** [comment]
Actually there's one more error but i resolve it by copying 'cmake' folder from openspades repo

**Comment by siecvi** [comment]
Probably fixed by 371e5e4 and e8b2a67?
